name: Build Android

on:
  push:
    branches:    
      - develop

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
          install-java: false
          install-pods: false

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Install NPM Modules
        run: |
          npm i -D -E @angular/cli
          npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Build Android Dev APK
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: ionic capacitor build android

      - name: Build Android Release APK
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Upload dev APK
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: |
            ${{ github.workspace }}/**/*.apk

      - name: Upload release bundle
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: |
            ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk